import "./globals.css";

export const metadata = {
  title: "ZusTand",
  description: "Generated by ZusTand and Next.JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
